import { Poppins } from "next/font/google";
import { PropsWithChildren } from "react";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "EchoNet",
  description: "Generated by create next app",
};

const font = Poppins({ subsets: ["latin"], weight: ["400", "600"] });

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={`${font.className} antialiased`}>{children}</body>
    </html>
  );
}
